apiVersion: apps/v1
kind: Deployment
metadata:
  name: .bk
  labels:
    app: .bk
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: .bk
  template:
    metadata:
      labels:
        app: .bk
    spec:
      containers:
        - name: .bk
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.kafkaPort }}
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:{{ .Values.service.zookeeperPort }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://.bk:{{ .Values.service.kafkaPort }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
