apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.zookeeperPort }}
      targetPort: {{ .Values.service.zookeeperPort }}
      protocol: TCP
  selector:
    app: zookeeper
