apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.zookeeperPort }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.service.zookeeperPort | quote }}"
