version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
  spark:
    build: ./spark_job
    depends_on:
      - kafka
    environment:
      SPARK_MASTER_URL: spark://localhost:7077
  airflow:
    image: apache/airflow:2.6.0
    ports:
      - "8080:8080"
    depends_on:
      - spark
